# this will run as default profile


chuck:
  norris:
#    api: https://api.chucknorris.io/jokes/random
     api: https://api.chucknorris.io/jokes/random?category={category}
#spring:
#  profiles:
#    active: dev

#logging:
#  level:
#    root: ERROR