spring.application.name=Journal App

#mongodb config

#spring.data.mongodb.uri=mongodb://localhost:27017/journaldb

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=journaldb
spring.data.mongodb.auto-index-creation=true

#spring.data.mongodb.uri=mongodb+srv://statusmood26:VqjnJ5ZtbKZF7E85@cluster0.zyn1rqt.mongodb.net/journaldb?retryWrites=true&w=majority

#spring.data.mongodb.database=myjournaluser
#spring.data.mongodb.password=mypassword